---
title             : "Method Section: Measures and Descriptive Statistics Write-up"
shorttitle        : "housework analysis"

author: 
  - name          : "Carlotta Reinhardt"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author

  - name          : "Margaret Bassney"
    affiliation   : "2"
    
   - name          : "Anushree Goswami"
    affiliation   : "2"


affiliation:
  - id            : "1"
    institution   : "Smith College"
  - id            : "2"
    institution   : "Smith College"
  - id            : "3"
    institution   : "Smith College"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```


# Method
## Measures


# Results
## Participant Demographics



\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
